buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.79.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'

rootProject.name = "suppressible-error-prone-root"

includeBuild 'artifact-transforms'
include 'gradle-suppressible-error-prone'
include 'suppressible-error-prone'
include 'test-error-prone-checks'

throw new RuntimeException('''The excavator failed to run properly:\n\n''' + file('gradle/exception').text)
