apply plugin: 'groovy'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.external-publish-gradle-plugin'

dependencies {
    api 'net.ltgt.gradle:gradle-errorprone-plugin'
    
    implementation 'org.ow2.asm:asm'
    implementation 'com.palantir.gradle.utils:environment-variables'

    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'commons-io:commons-io'
    testImplementation 'com.google.guava:guava'
    testImplementation 'one.util:streamex'
}

gradlePlugin {
    website = 'https://github.com/palantir/suppressible-error-prone'
    vcsUrl = 'https://github.com/palantir/suppressible-error-prone'

    plugins {
        suppressibleErrorProne {
            id = 'com.palantir.suppressible-error-prone'
            displayName = 'Suppressible Error Prone'
            description = 'Extends the Gradle Error Prone Plugin and Error Prone itself to support automatically suppressing errors.'
            tags = ['error-prone', 'javac', 'suppression']
            implementationClass = 'com.palantir.gradle.suppressibleerrorprone.SuppressibleErrorPronePlugin'
        }
    }
}

test {
    systemProperty 'ignoreDeprecations', 'true'
    systemProperty 'projectVersion', project.version
}

// Added as a jar the errorprone configuration inside the plugin, so in nebula-tests needs to exist in maven local
tasks.test.dependsOn ':suppressible-error-prone:publishToMavenLocal'

tasks.withType(JavaCompile) {
    options.errorprone {
        disable('StrictUnusedVariable')
    }
}

gradleTestUtils {
    gradleVersions = ['7.6.5', '8.14.2']
}
